[build]
  command = "npm run build"
  publish = "dist"

# Permet d'accéder directement aux HTML produits par Vite
[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/login.html"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/index"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/index.html"
  status = 200

# 🔥 Très IMPORTANT :
# On inclut le fallback pour *UNIQUEMENT* ce qui n'est pas un fichier existant
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Role = ["!stati]()
